version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: star_signs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  postgres-data:
