import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          <nav className="bg-blue-500 py-2">
            <NavbarComponent />
          </nav>
          <main className="min-h-screen bg-gradient-to-r from-blue-400 to-indigo-500">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
