version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: star_signs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d star_signs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: ${NODE_ENV:-production} # 使用環境變量來決定構建目標
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/star_signs_db?schema=public"
      NODE_ENV: ${NODE_ENV:-production}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ${NODE_ENV:-production} == 'development' && npm run dev || npm start

volumes:
  postgres-data:
