version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: star_signs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5435/star_signs_db?schema=public"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  postgres-data:
